### ISSUE TITLE
Test failures using Rubygems 1.6.2

### ISSUE THREAD

**Issue by chrisroos** [freerange/mocha#255]
```
$ ruby --version
ruby 1.8.7 (2011-06-30 patchlevel 352) [i686-darwin15.0.0]

$ gem --version
1.6.2

$ ruby -Itest test/acceptance/bug_18914_test.rb 
/Users/chrisroos/Code/freerange/mocha/lib/mocha/ruby_version.rb:2: uninitialized constant Mocha::Gem (NameError)
    from /Users/chrisroos/Code/freerange/mocha/test/assertions.rb:1:in `require'
    from /Users/chrisroos/Code/freerange/mocha/test/assertions.rb:1
    from /Users/chrisroos/Code/freerange/mocha/test/test_runner.rb:1:in `require'
    from /Users/chrisroos/Code/freerange/mocha/test/test_runner.rb:1
    from /Users/chrisroos/Code/freerange/mocha/test/acceptance/acceptance_test_helper.rb:2:in `require'
    from /Users/chrisroos/Code/freerange/mocha/test/acceptance/acceptance_test_helper.rb:2
    from test/acceptance/bug_18914_test.rb:1:in `require'
    from test/acceptance/bug_18914_test.rb:1
```

Adding `require 'rubygems'` to the top of ruby_version.rb appears to fix the problem but we're not convinced that this is a good idea as we don't necessarily want to tie the project to Rubygems.

**Comment by chrisroos** [comment]
I'm less convinced this is a problem now.

I see the same failure using Rubygems 2.6.6. However, if I use `bundle exec` then the problem goes away. I suspect using `bundle exec` with Rubygems 1.6.2 may also have solved the problem.

**Comment by floehopper** [comment]
This seems like a non-issue. Closing.
