### ISSUE TITLE
Test failures on Mac OSX Catalina - syscall() function is unimplemented on this machine

### ISSUE THREAD

**Issue by floehopper** [freerange/mocha#413]
I recently upgraded my laptop from Mac OSX High Sierra (v10.13) -> Catalina (v10.15) and since then I've been seeing the following test failures at least on the latest Ruby (v2.6.5):

```
  1) Error:
MockTest#test_should_be_able_to_mock_standard_object_methods:
NotImplementedError: syscall() function is unimplemented on this machine
    /Users/jamesmead/Code/freerange/mocha/test/unit/mock_test.rb:70:in `syscall'
    /Users/jamesmead/Code/freerange/mocha/test/unit/mock_test.rb:70:in `block in test_should_be_able_to_mock_standard_object_methods'
    /Users/jamesmead/Code/freerange/mocha/test/unit/mock_test.rb:70:in `each'
    /Users/jamesmead/Code/freerange/mocha/test/unit/mock_test.rb:70:in `test_should_be_able_to_mock_standard_object_methods'

  2) Error:
MockTest#test_should_be_able_to_stub_standard_object_methods:
NotImplementedError: syscall() function is unimplemented on this machine
    /Users/jamesmead/Code/freerange/mocha/test/unit/mock_test.rb:77:in `syscall'
    /Users/jamesmead/Code/freerange/mocha/test/unit/mock_test.rb:77:in `block in test_should_be_able_to_stub_standard_object_methods'
    /Users/jamesmead/Code/freerange/mocha/test/unit/mock_test.rb:77:in `each'
    /Users/jamesmead/Code/freerange/mocha/test/unit/mock_test.rb:77:in `test_should_be_able_to_stub_standard_object_methods'
```

Since the Travis CI builds don't appear to be failing, I strongly suspect this is a Mac OSX related problem.

**Comment by floehopper** [comment]
Fixed in #417. Closing.
